### ISSUE TITLE
Should the process be fully automatic or semiautomatic?

### ISSUE THREAD

**Issue by cclauss** [dhruvmanila/algobot#3]
I am OK either way.
1. Collect all intended actions and post that to a  task file in a PR?
2. Wait for a maintainer (or two maintainers?) to approve that PR.
3. Execute the intended actions and close the PR created in 1. above.

**Comment by cclauss** [comment]
Let's put it in place in automatic mode on TheAlgorithms/Python so we can get the number of open PRs down to a reasonable size.

Another thing to consider would be a throttle like "Each time that algobot is run, it can only close up to 10% of the open PRs.".

**Comment by dhruvmanila** [comment]
The way the bot works is based on GitHub webhook events. The bot is always on, listening to what GitHub is going to send. So, whenever some sort of event happens provided the app is subscribed to that event, like a pull request being opened, closed, labelled, unlabelled, etc. or an issue being opened, closed, labelled, assigned, etc. the bot receives a `POST` request from GitHub with all the necessary data as the payload. 

The library `gidgethub` is used to redirect the payload based on the event type to the registered function and then the function is used to do whatever necessary steps based on the event type. The same library is used to make all the necessary API calls as well. [This is the data](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-example-30) we get when a pull request is opened.

The bot won't run on all the PRs as it is programmed to listen and respond. If you want to do something for one time then that should be done locally with a simple script. Currently, the bot will run on the following events:
- `check_run: completed` when a single test is completed. Check whether all the checks for the PR is completed and only then determine the outcome of all the checks combined.
- `pull_request: opened` check description if it is empty, check for checklist, check if user already has an open PR, close PR if any of the previous condition is satisfied. Parse all the Python files and label and comment the report.
- `pull_request: synchronize` whenever a PR is updated (new commits are pushed) parse all the Python files again and label or unlabel accordingly. (Comment is only on the open event)

Reference:
GitHub webhook events: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads

**Comment by cclauss** [comment]
Nice!  The immediate feedback will be great.

**Comment by dhruvmanila** [comment]
If you have the Heroku CLI then probably you can take a look at all the logs: `heroku logs -a algorithms-bot`
I still have to add a good amount of `print` statements for logging.

**Comment by cclauss** [comment]
https://docs.python.org/3/library/logging.html --> https://docs.python.org/3/howto/logging.html

**Comment by dhruvmanila** [comment]
Yes I know about the module, it's just that when we `print`, Heroku is going to put that in its log for us to see it.
